"""create Enclosure instances

Revision ID: 9627a0d4898e
Revises: a0ec22a78b75
Create Date: 2024-09-19 21:41:33.263851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9627a0d4898e'
down_revision: Union[str, None] = 'a0ec22a78b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
